name: 'SWE-agent Issue Handler'
description: 'Automatically handle issues with SWE-agent'
inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true
  openai_api_key:
    description: 'OpenAI API key for SWE-agent'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
    - run: |
        python run.py --model_name gpt4 \
          --data_path ${{ github.event.issue.html_url }} \
          --config_file config/default_from_url.yaml \
          --output_format markdown \
          --output_path output.md
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    - uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const fs = require('fs');
          const output = fs.readFileSync('output.md', 'utf8');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
