site_name: SWE-agent documentation
theme:
  name: material
  logo: assets/swe-agent.svg

  palette: 



    # Palette toggle for light mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night

        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Home: index.md
  - Installation:
    - "Use in-browser": "installation/codespaces.md"
    - "Install from source": "installation/source.md"
    - "Docker": "installation/docker.md"
    - "Adding your keys": "installation/keys.md"
    - "Installation tips": "installation/tips.md"
  - Usage:
    - "Command line usage": "usage/cl_tutorial.md"
    - "Using the web UI": "usage/web_ui.md"
    - "Benchmarking": "usage/benchmarking.md"
  - Development:
    - "Modifying swe-agent": "modify.md"
    - "Contribution guide": "dev.md"



