site_name: SWE-agent documentation
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Home: index.md
  - Installation:
    - "Use in-browser": "installation/codespaces.md"
    - "Install from source": "installation/source.md"
    - "Docker": "installation/docker.md"
    - "Adding your keys": "installation/keys.md"
    - "Common issues": "installation/issues.md"
  - Usage:
    - "Command line usage": "usage/cl_tutorial.md"
    - "Using the web UI": "usage/web_ui.md"
  - Development:
    - "Modifying swe-agent": "modify.md"
    - "Contribution guide": "dev.md"



